### ISSUE TITLE
URL Naming standards

### ISSUE THREAD

**Issue by jpic** [codingjoe/django-cc#3]
There's an article about url naming standards: http://blog.yourlabs.org/post/20517779178/coding-standards-for-django-apps-names Many apps are like that, maybe we want this included in django-cc ?

**Comment by codingjoe** [comment]
@jpic thanks, I'll look into it. It's actually very similar, to what is already written down. I guess it just needs to be changed a little bit.

**Comment by jpic** [comment]
If you like it I can make a PR for that.

**Comment by codingjoe** [comment]
Yes, I'd love that!

**Comment by jpic** [comment]
Nah your current version is a lot better after all, I didn't remember that post was that old xD I've updated the article with a link to django-cc instead, it made me realise how cool it was to collaborate on this sort of stuff, I've got my first upgrade ^^ thanksssss

**Comment by jpic** [comment]
Nice win B)

**Comment by codingjoe** [comment]
ok, thanks
