### ISSUE TITLE
yourapp/base.html template

### ISSUE THREAD

**Issue by jpic** [codingjoe/django-cc#4]
In Pinax ecosystem, all apps templates should extend "appname/base.html". This allows to re-sort blocks, so I could do something like this in my project:

mytemplates/appname/base.html

```
{% extends 'mybase.html' %}
{% block mycontentblock %}{# block my template uses #}
{% block body %}{# block the app uses #}
{% endblock %}
{% endblock %}
```

Do you think a PR for that would be considered for inclusion ?

**Comment by codingjoe** [comment]
Again, tho I think this is a standard worth looking into, I don't know if it is ready to be included in a contributing guideline. It would become more interesting someone would write a separate standard for it.

**Comment by jpic** [comment]
Ok so maybe we could merge both issue about template since they are pretty related and have the same state, what do you think ?

**Comment by codingjoe** [comment]
I'd leave them separated. They are two different things, tho they might make sense together.
